/**
 * Extra domains for SEO discovery, added in bulk. Generated by appending
 * from new-domains.txt, so it is safe to re-run the import. Keep the
 * one-entry-per-line format below; the import reads it back.
 */

import type { SeoDomain } from "./seoDomains";

export const EXTRA_SEO_DOMAINS: SeoDomain[] = [
  { domain: "leagueoflegends.com", category: "Gaming" },
  { domain: "plex.tv", category: "Streaming" },
  { domain: "verizon.com", category: "Telecom" },
  { domain: "att.com", category: "Telecom" },
  { domain: "t-mobile.com", category: "Telecom" },
  { domain: "xfinity.com", category: "Telecom" },
  { domain: "spectrum.com", category: "Telecom" },
  { domain: "comcast.com", category: "Telecom" },
  { domain: "cox.com", category: "Telecom" },
  { domain: "vodafone.co.uk", category: "Telecom" },
  { domain: "bt.com", category: "Telecom" },
  { domain: "sky.com", category: "Telecom" },
  { domain: "rogers.com", category: "Telecom" },
  { domain: "bell.ca", category: "Telecom" },
  { domain: "jetblue.com", category: "Airlines" },
  { domain: "airnz.co.nz", category: "Airlines" },
  { domain: "easyjet.com", category: "Airlines" },
  { domain: "deliveroo.co.uk", category: "Food Delivery" },
  { domain: "instacart.com", category: "Food Delivery" },
  { domain: "irs.gov", category: "Government" },
  { domain: "gov.uk", category: "Government" },
  { domain: "canada.ca", category: "Government" },
  { domain: "ssa.gov", category: "Government" },
  { domain: "healthcare.gov", category: "Government" },
];
