/**
 * The popular sites list, in rank order (1 = most popular).
 * Used for the homepage grid (Top 50 / Top 100 filters), outage alerts
 * (top 50 only), and the sitemap (one /site/ page each).
 *
 * To add a site: add a line anywhere, and its position sets its rank.
 * Prefer sites that answer automated checks normally. Some big retailers
 * block or stall bots, which shows up as false "down" results.
 * Contains no data-sensitive info or security logic.
 */

export interface ListedSite {
  domain: string;
  name: string;
  category: string;
}

export const POPULAR_SITES: ListedSite[] = [
  { domain: "google.com", name: "Google", category: "Search" },
  { domain: "youtube.com", name: "YouTube", category: "Video" },
  { domain: "facebook.com", name: "Facebook", category: "Social" },
  { domain: "instagram.com", name: "Instagram", category: "Social" },
  { domain: "whatsapp.com", name: "WhatsApp", category: "Chat" },
  { domain: "x.com", name: "X (Twitter)", category: "Social" },
  { domain: "chatgpt.com", name: "ChatGPT", category: "AI" },
  { domain: "wikipedia.org", name: "Wikipedia", category: "Reference" },
  { domain: "reddit.com", name: "Reddit", category: "Social" },
  { domain: "amazon.com", name: "Amazon", category: "Shopping" },
  { domain: "tiktok.com", name: "TikTok", category: "Social" },
  { domain: "netflix.com", name: "Netflix", category: "Streaming" },
  { domain: "linkedin.com", name: "LinkedIn", category: "Social" },
  { domain: "microsoft.com", name: "Microsoft", category: "Tech" },
  { domain: "outlook.com", name: "Outlook", category: "Email" },
  { domain: "gmail.com", name: "Gmail", category: "Email" },
  { domain: "yahoo.com", name: "Yahoo", category: "Portal" },
  { domain: "bing.com", name: "Bing", category: "Search" },
  { domain: "discord.com", name: "Discord", category: "Chat" },
  { domain: "twitch.tv", name: "Twitch", category: "Streaming" },
  { domain: "spotify.com", name: "Spotify", category: "Music" },
  { domain: "paypal.com", name: "PayPal", category: "Payments" },
  { domain: "github.com", name: "GitHub", category: "Dev" },
  { domain: "apple.com", name: "Apple", category: "Tech" },
  { domain: "icloud.com", name: "iCloud", category: "Cloud" },
  { domain: "zoom.us", name: "Zoom", category: "Work" },
  { domain: "pinterest.com", name: "Pinterest", category: "Social" },
  { domain: "ebay.com", name: "eBay", category: "Shopping" },
  { domain: "roblox.com", name: "Roblox", category: "Gaming" },
  { domain: "steampowered.com", name: "Steam", category: "Gaming" },
  { domain: "epicgames.com", name: "Epic Games", category: "Gaming" },
  { domain: "playstation.com", name: "PlayStation", category: "Gaming" },
  { domain: "xbox.com", name: "Xbox", category: "Gaming" },
  { domain: "snapchat.com", name: "Snapchat", category: "Social" },
  { domain: "telegram.org", name: "Telegram", category: "Chat" },
  { domain: "cloudflare.com", name: "Cloudflare", category: "Infra" },
  { domain: "dropbox.com", name: "Dropbox", category: "Cloud" },
  { domain: "office.com", name: "Microsoft 365", category: "Work" },
  { domain: "slack.com", name: "Slack", category: "Work" },
  { domain: "canva.com", name: "Canva", category: "Tools" },
  { domain: "claude.ai", name: "Claude", category: "AI" },
  { domain: "gemini.google.com", name: "Gemini", category: "AI" },
  { domain: "threads.com", name: "Threads", category: "Social" },
  { domain: "quora.com", name: "Quora", category: "Social" },
  { domain: "imdb.com", name: "IMDb", category: "Entertainment" },
  { domain: "hulu.com", name: "Hulu", category: "Streaming" },
  { domain: "disneyplus.com", name: "Disney+", category: "Streaming" },
  { domain: "max.com", name: "Max", category: "Streaming" },
  { domain: "primevideo.com", name: "Prime Video", category: "Streaming" },
  { domain: "walmart.com", name: "Walmart", category: "Shopping" },
  { domain: "aliexpress.com", name: "AliExpress", category: "Shopping" },
  { domain: "temu.com", name: "Temu", category: "Shopping" },
  { domain: "shein.com", name: "SHEIN", category: "Shopping" },
  { domain: "etsy.com", name: "Etsy", category: "Shopping" },
  { domain: "adobe.com", name: "Adobe", category: "Tools" },
  { domain: "openai.com", name: "OpenAI", category: "AI" },
  { domain: "shopify.com", name: "Shopify", category: "Business" },
  { domain: "stripe.com", name: "Stripe", category: "Payments" },
  { domain: "venmo.com", name: "Venmo", category: "Payments" },
  { domain: "cash.app", name: "Cash App", category: "Payments" },
  { domain: "coinbase.com", name: "Coinbase", category: "Crypto" },
  { domain: "binance.com", name: "Binance", category: "Crypto" },
  { domain: "bbc.com", name: "BBC", category: "News" },
  { domain: "cnn.com", name: "CNN", category: "News" },
  { domain: "nytimes.com", name: "New York Times", category: "News" },
  { domain: "theguardian.com", name: "The Guardian", category: "News" },
  { domain: "espn.com", name: "ESPN", category: "Sports" },
  { domain: "weather.com", name: "The Weather Channel", category: "Weather" },
  { domain: "booking.com", name: "Booking.com", category: "Travel" },
  { domain: "airbnb.com", name: "Airbnb", category: "Travel" },
  { domain: "uber.com", name: "Uber", category: "Travel" },
  { domain: "doordash.com", name: "DoorDash", category: "Food" },
  { domain: "ubereats.com", name: "Uber Eats", category: "Food" },
  { domain: "soundcloud.com", name: "SoundCloud", category: "Music" },
  { domain: "duolingo.com", name: "Duolingo", category: "Education" },
  { domain: "notion.so", name: "Notion", category: "Work" },
  { domain: "figma.com", name: "Figma", category: "Design" },
  { domain: "trello.com", name: "Trello", category: "Work" },
  { domain: "atlassian.com", name: "Atlassian", category: "Work" },
  { domain: "gitlab.com", name: "GitLab", category: "Dev" },
  { domain: "stackoverflow.com", name: "Stack Overflow", category: "Dev" },
  { domain: "vercel.com", name: "Vercel", category: "Infra" },
  { domain: "aws.amazon.com", name: "AWS", category: "Infra" },
  { domain: "azure.microsoft.com", name: "Azure", category: "Infra" },
  { domain: "heroku.com", name: "Heroku", category: "Infra" },
  { domain: "digitalocean.com", name: "DigitalOcean", category: "Infra" },
  { domain: "godaddy.com", name: "GoDaddy", category: "Infra" },
  { domain: "wordpress.com", name: "WordPress.com", category: "Tools" },
  { domain: "medium.com", name: "Medium", category: "Reference" },
  { domain: "tumblr.com", name: "Tumblr", category: "Social" },
  { domain: "vk.com", name: "VK", category: "Social" },
  { domain: "bsky.app", name: "Bluesky", category: "Social" },
  { domain: "signal.org", name: "Signal", category: "Chat" },
  { domain: "teams.microsoft.com", name: "Microsoft Teams", category: "Work" },
  { domain: "minecraft.net", name: "Minecraft", category: "Gaming" },
  { domain: "ea.com", name: "EA", category: "Gaming" },
  { domain: "riotgames.com", name: "Riot Games", category: "Gaming" },
  { domain: "battle.net", name: "Battle.net", category: "Gaming" },
  { domain: "nintendo.com", name: "Nintendo", category: "Gaming" },
  { domain: "fortnite.com", name: "Fortnite", category: "Gaming" },
];
