/**
 * Additional well-known sites, beyond the ranked Top 100 in lib/sites.ts.
 * Used only to widen the "Having problems right now" panel so it can
 * surface outages on sites people care about even when they are not in
 * the ranked Top 100 grid. Not shown in the homepage grid, not part of
 * the sitemap, and does not affect any site's rank.
 * Prefer sites that answer automated checks normally.
 */

import type { ListedSite } from "@/lib/sites";

export const EXTRA_WATCH_SITES: ListedSite[] = [
  { domain: "chase.com", name: "Chase", category: "Banking" },
  { domain: "bankofamerica.com", name: "Bank of America", category: "Banking" },
  { domain: "wellsfargo.com", name: "Wells Fargo", category: "Banking" },
  { domain: "citibank.com", name: "Citibank", category: "Banking" },
  { domain: "capitalone.com", name: "Capital One", category: "Banking" },
  { domain: "americanexpress.com", name: "American Express", category: "Banking" },
  { domain: "target.com", name: "Target", category: "Shopping" },
  { domain: "bestbuy.com", name: "Best Buy", category: "Shopping" },
  { domain: "homedepot.com", name: "Home Depot", category: "Shopping" },
  { domain: "lowes.com", name: "Lowe's", category: "Shopping" },
  { domain: "costco.com", name: "Costco", category: "Shopping" },
  { domain: "ikea.com", name: "IKEA", category: "Shopping" },
  { domain: "nike.com", name: "Nike", category: "Shopping" },
  { domain: "sephora.com", name: "Sephora", category: "Shopping" },
  { domain: "starbucks.com", name: "Starbucks", category: "Food" },
  { domain: "mcdonalds.com", name: "McDonald's", category: "Food" },
  { domain: "chipotle.com", name: "Chipotle", category: "Food" },
  { domain: "dominos.com", name: "Domino's", category: "Food" },
  { domain: "grubhub.com", name: "Grubhub", category: "Food" },
  { domain: "instacart.com", name: "Instacart", category: "Food" },
  { domain: "lyft.com", name: "Lyft", category: "Travel" },
  { domain: "expedia.com", name: "Expedia", category: "Travel" },
  { domain: "tripadvisor.com", name: "TripAdvisor", category: "Travel" },
  { domain: "kayak.com", name: "Kayak", category: "Travel" },
  { domain: "united.com", name: "United Airlines", category: "Travel" },
  { domain: "delta.com", name: "Delta", category: "Travel" },
  { domain: "aa.com", name: "American Airlines", category: "Travel" },
  { domain: "southwest.com", name: "Southwest", category: "Travel" },
  { domain: "marriott.com", name: "Marriott", category: "Travel" },
  { domain: "hilton.com", name: "Hilton", category: "Travel" },
  { domain: "usps.com", name: "USPS", category: "Shipping" },
  { domain: "fedex.com", name: "FedEx", category: "Shipping" },
  { domain: "ups.com", name: "UPS", category: "Shipping" },
  { domain: "att.com", name: "AT&T", category: "Telecom" },
  { domain: "verizon.com", name: "Verizon", category: "Telecom" },
  { domain: "t-mobile.com", name: "T-Mobile", category: "Telecom" },
  { domain: "xfinity.com", name: "Xfinity", category: "Telecom" },
  { domain: "spectrum.com", name: "Spectrum", category: "Telecom" },
  { domain: "peacocktv.com", name: "Peacock", category: "Streaming" },
  { domain: "paramountplus.com", name: "Paramount+", category: "Streaming" },
  { domain: "crunchyroll.com", name: "Crunchyroll", category: "Streaming" },
  { domain: "craigslist.org", name: "Craigslist", category: "Shopping" },
  { domain: "indeed.com", name: "Indeed", category: "Jobs" },
  { domain: "glassdoor.com", name: "Glassdoor", category: "Jobs" },
  { domain: "ziprecruiter.com", name: "ZipRecruiter", category: "Jobs" },
  { domain: "salesforce.com", name: "Salesforce", category: "Business" },
  { domain: "hubspot.com", name: "HubSpot", category: "Business" },
  { domain: "zendesk.com", name: "Zendesk", category: "Business" },
  { domain: "monday.com", name: "monday.com", category: "Work" },
  { domain: "airtable.com", name: "Airtable", category: "Work" },
  { domain: "docusign.com", name: "DocuSign", category: "Business" },
  { domain: "box.com", name: "Box", category: "Cloud" },
  { domain: "protonmail.com", name: "Proton Mail", category: "Email" },
  { domain: "aol.com", name: "AOL", category: "Portal" },
  { domain: "zoho.com", name: "Zoho", category: "Business" },
  { domain: "squarespace.com", name: "Squarespace", category: "Tools" },
  { domain: "wix.com", name: "Wix", category: "Tools" },
  { domain: "mailchimp.com", name: "Mailchimp", category: "Tools" },
  { domain: "calendly.com", name: "Calendly", category: "Tools" },
  { domain: "zillow.com", name: "Zillow", category: "Real Estate" },
  { domain: "redfin.com", name: "Redfin", category: "Real Estate" },
  { domain: "realtor.com", name: "Realtor.com", category: "Real Estate" },
  { domain: "yelp.com", name: "Yelp", category: "Reference" },
  { domain: "walgreens.com", name: "Walgreens", category: "Shopping" },
  { domain: "cvs.com", name: "CVS", category: "Shopping" },
  { domain: "gamestop.com", name: "GameStop", category: "Shopping" },
  { domain: "kohls.com", name: "Kohl's", category: "Shopping" },
  { domain: "macys.com", name: "Macy's", category: "Shopping" },
  { domain: "nordstrom.com", name: "Nordstrom", category: "Shopping" },
  { domain: "asos.com", name: "ASOS", category: "Shopping" },
  { domain: "chess.com", name: "Chess.com", category: "Gaming" },
  { domain: "ign.com", name: "IGN", category: "Entertainment" },
  { domain: "theverge.com", name: "The Verge", category: "News" },
  { domain: "techcrunch.com", name: "TechCrunch", category: "News" },
  { domain: "wired.com", name: "Wired", category: "News" },
  { domain: "arstechnica.com", name: "Ars Technica", category: "News" },
  { domain: "engadget.com", name: "Engadget", category: "News" },
  { domain: "cnet.com", name: "CNET", category: "News" },
  { domain: "forbes.com", name: "Forbes", category: "News" },
  { domain: "businessinsider.com", name: "Business Insider", category: "News" },
  { domain: "bloomberg.com", name: "Bloomberg", category: "News" },
  { domain: "wsj.com", name: "The Wall Street Journal", category: "News" },
  { domain: "reuters.com", name: "Reuters", category: "News" },
  { domain: "npr.org", name: "NPR", category: "News" },
  { domain: "foxnews.com", name: "Fox News", category: "News" },
  { domain: "usatoday.com", name: "USA Today", category: "News" },
  { domain: "washingtonpost.com", name: "The Washington Post", category: "News" },
];