# Usage (from the project folder):
#   powershell -ExecutionPolicy Bypass -File scripts\import-domains.ps1
# Reads new-domains.txt (domain or domain,Category per line) and appends
# new entries to seo_engine\data\seoDomainsExtra.ts. Safe to re-run.
$u = New-Object Text.UTF8Encoding($false)
$root = Split-Path -Parent $PSScriptRoot
$inFile = Join-Path $root "new-domains.txt"
$extraFile = Join-Path $root "seo_engine\data\seoDomainsExtra.ts"
if (-not (Test-Path $inFile)) { "Missing $inFile"; return }

$existing = @{}
foreach ($p in @((Join-Path $root "seo_engine\data\seoDomains.ts"), $extraFile, (Join-Path $root "lib\sites.ts"))) {
  foreach ($m in [regex]::Matches([IO.File]::ReadAllText($p), 'domain:\s*"([^"]+)"')) { $existing[$m.Groups[1].Value.ToLower()] = $true }
}
$entries = New-Object System.Collections.ArrayList
foreach ($m in [regex]::Matches([IO.File]::ReadAllText($extraFile), 'domain:\s*"([^"]+)",\s*category:\s*"([^"]+)"')) { [void]$entries.Add(@($m.Groups[1].Value, $m.Groups[2].Value)) }

$added = 0; $skipped = 0
foreach ($line in Get-Content $inFile -Encoding UTF8) {
  $line = $line.Trim()
  if (-not $line -or $line.StartsWith('#')) { continue }
  $parts = $line -split '[,\t]', 2
  $d = $parts[0].Trim().ToLower() -replace '^https?://', '' -replace '^www\.', '' -replace '/.*$', ''
  $cat = if ($parts.Count -gt 1 -and $parts[1].Trim()) { $parts[1].Trim() } else { 'Websites' }
  $cat = $cat -replace '["\\]', ''
  if ($d -notmatch '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$' -or $existing.ContainsKey($d)) { $skipped++; continue }
  $existing[$d] = $true
  [void]$entries.Add(@($d, $cat)); $added++
}

$sb = New-Object Text.StringBuilder
[void]$sb.AppendLine('/**')
[void]$sb.AppendLine(' * Extra domains for SEO discovery, added in bulk. Generated by appending')
[void]$sb.AppendLine(' * from new-domains.txt, so it is safe to re-run the import. Keep the')
[void]$sb.AppendLine(' * one-entry-per-line format below; the import reads it back.')
[void]$sb.AppendLine(' */')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('import type { SeoDomain } from "./seoDomains";')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('export const EXTRA_SEO_DOMAINS: SeoDomain[] = [')
foreach ($e in $entries) { [void]$sb.AppendLine('  { domain: "' + $e[0] + '", category: "' + $e[1] + '" },') }
[void]$sb.AppendLine('];')
[IO.File]::WriteAllText($extraFile, $sb.ToString(), $u)
"added $added, skipped $skipped, total extras $($entries.Count)"